AWSTemplateFormatVersion: 2010-09-09
Description: A template for a Python-based Config Rule deployed to AWS Lambda.

Transform:
- AWS::Serverless-2016-10-31
- AWS::CodeStar

Parameters:
  ProjectId:
    Type: String
    Description: AWS CodeStar projectID is used to associate new resources to this project.

# Enable blue/green deployments using this Globals section. For instructions, see the AWS CodeStar User Guide:
# https://docs.aws.amazon.com/codestar/latest/userguide/how-to-modify-serverless-project.html?icmpid=docs_acs_rm_tr
#
# Globals:
#   Function:
#     AutoPublishAlias: live
#     DeploymentPreference:
#       Enabled: true
#       Type: Canary10Percent5Minutes

Resources:
  ConfigRuleLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      Principal: config.amazonaws.com
      FunctionName:
        Ref: ConfigRuleLambdaFunction
  ConfigRuleLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: rule_code.lambda_handler
      Runtime: python3.6
      Role:
        Fn::ImportValue:
          !Join ['-', [!Ref 'ProjectId', !Ref 'AWS::Region', 'LambdaTrustRole']]
  ConfigRule:
    DependsOn: ConfigRuleLambdaPermission
    Type: AWS::Config::ConfigRule
    Properties:
      ConfigRuleName:
        Ref: ProjectId
      Description: Custom AWS Config Rule created with AWS Codestar to check whether your EC2 instances are of the specified instance type.
      InputParameters:
        desiredInstanceType: t2.micro
      Scope:
        ComplianceResourceTypes:
          - 'AWS::EC2::Instance'
      Source:
        Owner: CUSTOM_LAMBDA
        SourceIdentifier:
          Fn::GetAtt:
          - ConfigRuleLambdaFunction
          - Arn
        SourceDetails:
        - EventSource: aws.config
          MessageType: ConfigurationItemChangeNotification
        - EventSource: aws.config
          MessageType: OversizedConfigurationItemChangeNotification

